### ISSUE TITLE
Import one apt package scan entry into the database

### ISSUE THREAD

**Issue by greenmoss** [Doveps/old_bassist#3]
Goal: Read a line from the scanner output file for apt packages, and use the parser code to import the line into one of the database tables. 

You will need to look into the parser code at https://github.com/Doveps/bassist/blob/master/bassist/parser/log_file/debs_stdout.py

You can use an existing database table, or create a new one, as needed.

Reference the output from the scanner: (https://github.com/Doveps/scanner/issues/2)

**Comment by JosiahRegencia** [comment]
Oh my. I'm sorry. I didn't notice this ticket the last time. I'm sorry

**Comment by greenmoss** [comment]
No problem; this is ticket one for this week.

I'm going to be closing this ticket and moving it over to the consolidated repository today.

**Comment by greenmoss** [comment]
Bassist has moved into the monorepo; this issue has moved to https://github.com/Doveps/mono/issues/3
